---
- hosts: all
  become: yes
    
  tasks:
    - name: install updates on CentOS
      yum:
        update_only: true
        update_cache: true
      when: ansible_distribution == "CentOS"

    - name: install httpd and php packages for centos
      yum:
        name: 
          - httpd
          - php 
          - vim
        state: present
        update_cache: true
        update_only:  true
      when: ansible_distribution == "CentOS"
